### ISSUE TITLE
TypeScript types are broken under Node native ESM

### ISSUE THREAD

**Issue by ezzatron** [dubzzz/fast-check#4253]
## 🐛 Bug Report

When using `type-check` with TypeScript in a Node.js package with `"type": "module"` (native ESM), the types do not resolve.

## To Reproduce

Steps to reproduce:

- Clone https://github.com/ezzatron/fast-check-types-repro
- Run `npm ci`
- Run `npx tsc --noEmit -p tsconfig.json`
- Observe the following errors:

```
$ npx tsc --noEmit -p tsconfig.json
example.ts:1:10 - error TS2614: Module '"fast-check"' has no exported member 'double'. Did you mean to use 'import double from "fast-check"' instead?

1 import { double } from "fast-check"
           ~~~~~~

node_modules/fast-check/lib/esm/types/fast-check.d.ts:1:21 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

1 import * as fc from './fast-check-default';
                      ~~~~~~~~~~~~~~~~~~~~~~

node_modules/fast-check/lib/esm/types/fast-check.d.ts:3:15 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

3 export * from './fast-check-default';
                ~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors in 2 files.

Errors  Files
     1  example.ts:1
     2  node_modules/fast-check/lib/esm/types/fast-check.d.ts:1
```

You can also see this output in GitHub Actions: https://github.com/ezzatron/fast-check-types-repro/actions/runs/6289635563/job/17076317889#step:5:5

## Expected behavior

No TypeScript errors when using `"moduleResolution": "nodeNext"`. See https://www.typescriptlang.org/docs/handbook/esm-node.html

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           |    `3.13.0`        |
| node                 |     `20.7.0`       |
| TypeScript\*         |      `5.2.2`      |

\*Only for TypeScript's users

**Comment by dubzzz** [comment]
Good catch! I'll check that one soon. I have some ideas of what can go wrong, but I'll need to check I don't miss anything

**Comment by wvhulle** [comment]
I have the same problem. Downgrading to fastcheck 3.10 fixes it.

**Comment by dubzzz** [comment]
> Downgrading to fastcheck 3.10 fixes it

Thanks a lot for this hint, it will help me a lot. I have takn time yet to work on the fix but I hope to come up with one quickly in the week. I'll keep you posted.

**Comment by dubzzz** [comment]
Fix merged on main, I'll release it soon. Just waiting the other fixes to be merged too.

**Comment by dubzzz** [comment]
The version should be published soon! I launched the publication workflow.

**Comment by ezzatron** [comment]
Thanks for the fix, but I still can't use `fast-check` because `pure-rand` has the same problem: https://github.com/ezzatron/fast-check-types-repro/actions/runs/6325478237/job/17177067133#step:5:5

```
$ npx tsc --noEmit -p tsconfig.json
node_modules/fast-check/lib/esm/types/check/runner/configuration/Parameters.d.ts:4:10 - error TS2614: Module '"pure-rand"' has no exported member 'RandomGenerator'. Did you mean to use 'import RandomGenerator from "pure-rand"' instead?

4 import { RandomGenerator } from 'pure-rand';
           ~~~~~~~~~~~~~~~

node_modules/fast-check/lib/esm/types/random/generator/Random.d.ts:1:10 - error TS2614: Module '"pure-rand"' has no exported member 'RandomGenerator'. Did you mean to use 'import RandomGenerator from "pure-rand"' instead?

1 import { RandomGenerator } from 'pure-rand';
           ~~~~~~~~~~~~~~~

node_modules/pure-rand/lib/esm/types/pure-rand.d.ts:1:24 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

1 import * as prand from './pure-rand-default';
                         ~~~~~~~~~~~~~~~~~~~~~

node_modules/pure-rand/lib/esm/types/pure-rand.d.ts:3:15 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

3 export * from './pure-rand-default';
                ~~~~~~~~~~~~~~~~~~~~~


Found 4 errors in 3 files.

Errors  Files
     1  node_modules/fast-check/lib/esm/types/check/runner/configuration/Parameters.d.ts:4
     1  node_modules/fast-check/lib/esm/types/random/generator/Random.d.ts:1
     2  node_modules/pure-rand/lib/esm/types/pure-rand.d.ts:1
```

**Comment by dubzzz** [comment]
I'm addressing this one

**Comment by dubzzz** [comment]
This time it should be good. I just patched pure-rand!

And I confirmed it passes on your repro.

**Comment by ezzatron** [comment]
Thank you! Confirmed the fix on my end too 👍

**Comment by dubzzz** [comment]
Once again thanks a lot for this very clear repro
